global:
  scrape_interval: 10s
  evaluation_interval: 15s #how often to calculate metrics defined in recording_rules.yml
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090

 - job_name: grafana
   metrics_path: /metrics
   static_configs:
    - targets:
       - grafana:3000

 - job_name: java-app
   metrics_path: /actuator/prometheus
   static_configs:
    - targets:
       - java-app-a:8081
       - java-app-b:8081

 - job_name: nginx
   metrics_path: /metrics
   static_configs:
    - targets:
       - nginx-exporter:9113

 - job_name: dotnet-app
   metrics_path: /metrics
   static_configs:
    - targets:
       - dotnet-app:8081
       
rule_files:
  - /opt/bitnami/prometheus/conf/recording_rules.yml #location of file that specifies which default metrics should be configured
