services:
  prometheus:
    image: bitnami/prometheus:2.53.1
    networks:
      - monitoring101
    ports:
      - 9090:9090
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=users
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=1234file
    volumes:
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  # Login: admin/admin
  grafana:
    image: grafana/grafana:11.1.3
    networks:
      - monitoring101
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
networks:
  # To create this run: docker network create monitoring101
  monitoring101:
    external: true
